spring:
  application:
    name: salesmanagement

  datasource:
    url: jdbc:mysql://localhost:3306/jpa18?createDatabaseIfNotExist=true
    username: root
    password: ethio2025
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mvc:
    static-path-pattern: /static/**

server:
  port: 8083
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10  # Send heartbeats every 10s
    lease-expiration-duration-in-seconds: 30  # Remove instance if no heartbeat in 30s
# H2 Console (Uncomment if needed)
# h2:
#   console:
#     enabled: true
#     path: /h2-console
